package enums;

public enum FigurEnum {
    BAUER_WEISS, BAUER_SCHWARZ, PFERD_WEISS, PFERD_SCHWARZ, LAEUFER_WEISS, LAEFER_SCHWARZ, TURM_WEISS, TURM_SCHWARZ, DAME_WEISS, DAME_SCHWARZ, KOENIG_WEISS, KOENIG_SCHWARZ
}
